apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ghost
  name: ghost
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 2368
  selector:
    run: ghost
  type: LoadBalancer
status:
  loadBalancer: {}
