apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bad-nginx
  name: bad-nginx
spec:
  containers:
  - image: nginx:200
    name: bad-nginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
