apiVersion: v1
kind: Pod # this is a comment
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: training-b1 # optional. No need to -n in this case
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: 
      limits:
        cpu: 10m
        memory: 20Mi
      requests:
        cpu: 10m
        memory: 20Mi
  - image: ghost
    name: ghost
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
