apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      initContainers:
      - image: busybox
        name: init-dir
        command: 
        - /bin/sh
        - -c
        - "mkdir -p /init && echo 'hello' > /init/hello.txt"
        volumeMounts:
        - name: init-dir # should be equal to name of the volume
          mountPath: /init
      containers:
      - image: busybox
        name: busybox
        command:
        - /bin/sh
        - -c
        - "cat /app/hello.txt && sleep 3600;"
        resources: {}
      volumes:
      - name: init-dir
        emptyDir: {}
status: {}
