apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        command:
        - /bin/sh
        - -c
        - "sleep 3600;"
        resources: {}
        volumeMounts:
        - name: log-dir
          mountPath: /var/log # you can mount anywhere you want
      volumes:
      - name: log-dir
        hostPath:
          path: /var/log

status: {}
