apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: demo-app
  name: demo-app
spec:
  containers:
  - image: nj93/batch3-demo:v1
    name: demo-app
    ports:
    - containerPort: 8000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
