apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Changed CPU from 100 to 120"
  creationTimestamp: null
  labels:
    run: demo-app
  name: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: demo-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: demo-app
    spec:
      containers:
      - image: nj93/batch3-demo:v1
        name: demo-app
        ports:
        - containerPort: 8000
        resources: 
          # limits:
          #   cpu: 150m
          #   memory: 100Mi
          requests:
            cpu: 100m 
            memory: 80Mi
      terminationGracePeriodSeconds: 60
status: {}
