apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      containers:
      - image: busybox
        name: logs
        resources: {}
        command: ["bin/sh", "-c", "touch /app/hello.txt && sleep 3600"]
        volumeMounts:
        - name:  app-dir
          mountPath: /app
      volumes:
      - name: app-dir
        persistentVolumeClaim:
          claimName: test-pvc
status: {}
