apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/azure-disk
    volumehelper.VolumeDynamicallyCreatedByKey: azure-disk-dynamic-provisioner
  creationTimestamp: "2020-02-13T15:35:09Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-7c02857b-2bc7-46d7-bfa9-b13d6174efe3
spec:
  accessModes:
  - ReadWriteOnce
  azureDisk:
    cachingMode: ReadOnly
    diskName: kubernetes-dynamic-pvc-7c02857b-2bc7-46d7-bfa9-b13d6174efe3
    diskURI: /subscriptions/69605697-3046-4bc4-a607-f7313aa2d779/resourceGroups/mc_pxe-poc_pxe-test_eastus/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-7c02857b-2bc7-46d7-bfa9-b13d6174efe3
    fsType: ""
    kind: Managed
    readOnly: false
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test-pvc
    namespace: default
    resourceVersion: "3826597"
    uid: 7c02857b-2bc7-46d7-bfa9-b13d6174efe3
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  volumeMode: Filesystem

