
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bad
  labels:
    app: busybox # optional
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bad-name
  resources:
    requests:
      storage: 10Gi
     