apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
        command: 
        - bin/sh
        - -c
        - "sleep 3600;"
        envFrom:
        - secretRef:
           name: app-passwords
        volumeMounts:
        - name: any-name
          mountPath: /app
      volumes:
      - name: any-name
        secret: 
          secretName: app-passwords

status: {}
