apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      containers:
      - image: busybox:1.27
        name: busybox
        command:
        - /bin/sh
        - -c
        - "sleep 3600;"
        env:
        # - name: organization
        #   value: Platformer
        - name: country
          value: Australia
        - name: author-new
          valueFrom: 
            configMapKeyRef:
              key: author
              name: org-config
        envFrom:
        - configMapRef:
            name: org-config
        resources: {}
status: {}
