version: '3'
# This compose file is ONLY used for spinning up a local Postgres container for development.
services:
  demo-app:
    build: .
    ports:
      - '3000:8000'
    environment:
      - example=user
  postgres:
    image: 'postgres:12-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=rudder
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
volumes:
  postgres_data:
    driver: local
